//program on checked exception (not serious)
//ex (ArithmethmeticExpression, null point, Arrayindexoutofbounds)
//for checking exception try-catch is mandatory
//throws is an alternate solution for try-catch
//ignoring exception
package classobjectdemo;

public class test7 {

	public static void main(String[] args) throws Exception {
		
		System.out.println("Program begins");
		//throw new ArithmeticException("Division by zero");
		throw new InterruptedException("Thread Interruption");
		}
		
		}

	


